# Use official Node image
FROM node:18

# Working directory inside container
WORKDIR /app

# Copy package files first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project
COPY . .

# Expose the API port
EXPOSE 3000

# Start the app
CMD ["node", "index.js"]
